"""Reporting Agent — compiles weekly analysis into a structured digest."""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
PROCESSED_DIR = DATA_DIR / "processed"
REPORTS_DIR = DATA_DIR / "reports"

REPORT_TEMPLATE = """\
# Weekly Document Monitoring Digest
**Period:** {{ start_date }} — {{ end_date }}
**Generated:** {{ generated_at }}

---

## Summary
- **Documents Analyzed:** {{ documents | length }}
- **High Significance:** {{ high_count }}
- **Medium Significance:** {{ medium_count }}
- **Low Significance:** {{ low_count }}

---

## New Documents Detected
{% for doc in documents %}
### {{ loop.index }}. {{ doc.title }}
- **Source:** {{ doc.source_name }}
- **Type:** {{ doc.doc_type }}
- **Published:** {{ doc.published_date or "N/A" }}
- **Significance:** {{ doc.analysis.significance | default("N/A") }}

**Summary:** {{ doc.analysis.summary | default("No summary available.") }}

{% if doc.analysis.key_changes %}**Key Changes:** {{ doc.analysis.key_changes }}{% endif %}

{% if doc.analysis.topics %}**Topics:** {{ doc.analysis.topics | join(", ") }}{% endif %}

{% endfor %}

---

## Entity Highlights
{% for entity in all_entities %}
- {{ entity }}
{% endfor %}

---

## Trend Analysis
{% for topic, count in topic_counts.items() %}
- **{{ topic }}** — appeared in {{ count }} document(s)
{% endfor %}

---

*Generated by Document Monitoring Pipeline — Mu-Sigma*
"""


def _count_significance(analyses: list[dict], level: str) -> int:
    return sum(
        1
        for a in analyses
        if isinstance(a.get("analysis"), dict) and level in str(a["analysis"].get("significance", "")).lower()
    )


def _collect_entities(analyses: list[dict]) -> list[str]:
    entities: set[str] = set()
    for a in analyses:
        if isinstance(a.get("analysis"), dict):
            for e in a["analysis"].get("entities", []):
                entities.add(str(e))
    return sorted(entities)


def _collect_topic_counts(analyses: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for a in analyses:
        if isinstance(a.get("analysis"), dict):
            for t in a["analysis"].get("topics", []):
                counts[t] = counts.get(t, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: x[1], reverse=True))


def generate_report(analyses: list[dict], start_date: str, end_date: str) -> str:
    """Generate a markdown report from a list of analysis results."""
    template = Template(REPORT_TEMPLATE)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    report = template.render(
        start_date=start_date,
        end_date=end_date,
        generated_at=now,
        documents=analyses,
        high_count=_count_significance(analyses, "high"),
        medium_count=_count_significance(analyses, "medium"),
        low_count=_count_significance(analyses, "low"),
        all_entities=_collect_entities(analyses),
        topic_counts=_collect_topic_counts(analyses),
    )

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"digest_{end_date}.md"
    out_path = REPORTS_DIR / filename
    out_path.write_text(report)
    logger.info("Report written to %s", out_path)
    return report


def generate_from_latest_analysis() -> str:
    """Find the most recent analysis output and generate a report."""
    files = sorted(PROCESSED_DIR.glob("analysis_*.json"), reverse=True)
    if not files:
        logger.warning("No analysis files found")
        return ""
    with open(files[0]) as f:
        analyses = json.load(f)

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return generate_report(analyses, start_date="(auto)", end_date=today)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    report = generate_from_latest_analysis()
    if report:
        print(report)
    else:
        print("No analysis data available.")
